[package]
name = "udp-fanout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"
